import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import homeRouter from "./home";
import memoriesRouter from "./memories";
import memoryParticipantsRouter from "./memory-participants";
import peopleRouter from "./people";
import calendarRouter from "./calendar";
import futureGiftsRouter from "./future-gifts";
import storageRouter from "./storage";
import eventsRouter from "./events";
import notificationsRouter from "./notifications";
import connectionsRouter from "./connections";
import daylinksRouter from "./daylinks";
import scheduledMessagesRouter from "./scheduled-messages";
import globeRouter from "./globe";
import memoryDropsRouter from "./memory-drops";
import dailyPromptsRouter from "./daily-prompts";
import shareLinksRouter from "./share-links";
import relationshipEventsRouter from "./relationship-events";
import invitesRouter from "./invites";
import capsuleRouter from "./capsule";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(eventsRouter);
router.use(homeRouter);
router.use(memoriesRouter);
router.use(memoryParticipantsRouter);
router.use(peopleRouter);
router.use(calendarRouter);
router.use(futureGiftsRouter);
router.use(storageRouter);
router.use(notificationsRouter);
router.use(connectionsRouter);
router.use(daylinksRouter);
router.use(scheduledMessagesRouter);
router.use(globeRouter);
router.use(memoryDropsRouter);
router.use(dailyPromptsRouter);
router.use(shareLinksRouter);
router.use(relationshipEventsRouter);
router.use(invitesRouter);
router.use(capsuleRouter);

export default router;
